"""Deterministic fixture builders for remove-ai-marks tests.

Every fixture is generated in-memory (no binary blobs committed) so tests are
reproducible and diff-friendly. Builders are grouped by format family.
"""

from __future__ import annotations

import io
import struct
import zlib
import zipfile

SCRIPTS_DIR = None  # populated by conftest; builders do not need scripts

PNG_SIG = b"\x89PNG\r\n\x1a\n"
JPEG_SOI = b"\xff\xd8"


def _png_chunk(ctype: bytes, payload: bytes) -> bytes:
    crc = zlib.crc32(ctype)
    crc = zlib.crc32(payload, crc) & 0xFFFFFFFF
    return struct.pack(">I", len(payload)) + ctype + payload + struct.pack(">I", crc)


def build_png(
    *,
    with_c2pa: bool = False,
    with_exif: bool = False,
    with_xmp_text: bool = False,
) -> bytes:
    """2x2 solid-color PNG. Optional caBX (C2PA), eXIf, or tEXt/XMP chunks."""
    ihdr = _png_chunk(b"IHDR", struct.pack(">IIBBBBB", 2, 2, 8, 6, 0, 0, 0))
    idat = _png_chunk(b"IDAT", zlib.compress(b"\x00" + b"\xff\x00\x00" * 4))
    iend = _png_chunk(b"IEND", b"")
    chunks = [ihdr, idat]
    if with_c2pa:
        chunks.append(_png_chunk(b"caBX", b"jumb\x00\x01fake-c2pa-manifest"))
    if with_exif:
        exif = b"Exif\x00\x00II*\x00\x08\x00\x00\x00\x00"
        exif += b"\x00\x00\x00\x00Software\x00" + b"Claude v2" + b"\x00"
        chunks.append(_png_chunk(b"eXIf", exif))
    if with_xmp_text:
        chunks.append(
            _png_chunk(
                b"tEXt",
                b'Raw profile type xmp\x00<?xpacket begin="\xef\xbb\xbf" ?>'
                b"<x:xmpmeta xmlns:x='adobe:ns:meta/'><rdf:Description>"
                b"digitalSourceType: trainedAlgorithmicMedia</rdf:Description>"
                b"</x:xmpmeta>",
            )
        )
    chunks.append(iend)
    return PNG_SIG + b"".join(chunks)


def _jpeg_app(marker_byte: int, payload: bytes) -> bytes:
    return bytes([0xFF, marker_byte]) + struct.pack(">H", len(payload) + 2) + payload


def build_jpeg(
    *,
    with_c2pa: bool = False,
    with_exif: bool = False,
    with_xmp: bool = False,
) -> bytes:
    """Tiny structurally-valid JPEG (SOI + APP segments + minimal scan)."""
    out = bytearray(JPEG_SOI)
    if with_exif:
        out += _jpeg_app(
            0xE1,
            b"Exif\x00\x00" + b"II*\x00\x08\x00\x00\x00\x00" + b"Software\x00Claude\x00",
        )
    if with_xmp:
        out += _jpeg_app(
            0xE1,
            b"http://ns.adobe.com/xap/1.0/\x00"
            b'<?xpacket begin="\xef\xbb\xbf" ?><x:xmpmeta><rdf:Description>'
            b"trainedAlgorithmicMedia</rdf:Description></x:xmpmeta>",
        )
    if with_c2pa:
        out += _jpeg_app(0xEB, b"jumb\x00\x01fake-c2pa-manifest")
    # A minimal grey 1x1 JPEG scan: SOF0 + DHT + SOS + 1 entropy byte + EOI.
    out += bytes([0xFF, 0xC0]) + struct.pack(">HBBBB", 11, 8, 1, 1, 1)
    out += bytes([0xFF, 0xDD]) + struct.pack(">HB", 4, 0)
    out += bytes([0xFF, 0xC4]) + struct.pack(">HB", 19, 0x00)
    out += bytes(16)
    out += bytes([0xFF, 0xDA]) + struct.pack(">HB", 8, 1) + bytes([0, 0, 0, 3, 1, 0])
    out += b"\x80"
    out += b"\xff\xd9"
    return bytes(out)


def build_markdown(
    *,
    ai_generator: bool = False,
    ai_key: bool = False,
    zwsp: bool = False,
) -> bytes:
    fm: list[str] = []
    if ai_generator:
        fm.append("generator: Claude")
    if ai_key:
        fm.append("ai_generated: true")
    fm.append("title: Test")
    block = "\n".join(fm)
    body = "Hello body.\n"
    if zwsp:
        body = "Hello\u200bbody.\n"
    return f"---\n{block}\n---\n\n{body}".encode("utf-8")


def build_html(*, ai_meta: bool = False, jsonld: bool = False, data_ai: bool = False) -> bytes:
    metas = '<meta charset="utf-8">\n'
    if ai_meta:
        metas += '<meta name="generator" content="ChatGPT">\n'
    body = "<title>Page</title>\n<h1>Hi</h1>"
    script = ""
    if jsonld:
        script = (
            '<script type="application/ld+json">'
            '{"creator":{"@type":"Organization","name":"OpenAI"},'
            '"digitalSourceType":"trainedAlgorithmicMedia"}</script>'
        )
    attr = ' data-ai-model="gpt-4"' if data_ai else ""
    return f"<!doctype html><html><head>{metas}</head><body{attr}>{body}{script}</body></html>".encode("utf-8")


def build_svg(*, metadata: bool = False, xmp: bool = False, ai_comment: bool = False) -> bytes:
    meta = ""
    if metadata:
        meta = (
            "<metadata><rdf:RDF xmlns:rdf='http://www.w3.org/1999/02/22-rdf-syntax-ns#'>"
            "<rdf:Description>trainedAlgorithmicMedia</rdf:Description></rdf:RDF></metadata>"
        )
    if xmp:
        meta += (
            "<x:xmpmeta xmlns:x='adobe:ns:meta/'><rdf:Description>"
            "generator=Claude</rdf:Description></x:xmpmeta>"
        )
    comment = "<!-- generated by Claude -->" if ai_comment else ""
    return (
        f"<svg xmlns='http://www.w3.org/2000/svg' width='10' height='10'>"
        f"{meta}{comment}<rect width='10' height='10'/></svg>"
    ).encode("utf-8")


def build_docx(*, ai_creator: bool = False, custom_xml: bool = False, zwsp: bool = False) -> bytes:
    creator = "<dc:creator>Claude</dc:creator>" if ai_creator else "<dc:creator>Jane</dc:creator>"
    app = "<Application>Claude</Application>" if ai_creator else "<Application>Word</Application>"
    body = "<w:t>Hello</w:t>" if not zwsp else "<w:t>Hello\u200bWorld</w:t>"
    parts = {
        "[Content_Types].xml": (
            '<?xml version="1.0"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">'
            '<Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>'
            '<Override PartName="/customXml/item1.xml" ContentType="application/xml"/>'
            "</Types>"
        ),
        "_rels/.rels": (
            '<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'
            '<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/>'
            "</Relationships>"
        ),
        "word/document.xml": (
            '<?xml version="1.0"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">'
            f"<w:body><w:p><w:r>{body}</w:r></w:p></w:body></w:document>"
        ),
        "docProps/core.xml": (
            '<?xml version="1.0"?><cp:coreProperties xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/core-properties" '
            'xmlns:dc="http://purl.org/dc/elements/1.1/">'
            f"{creator}</cp:coreProperties>"
        ),
        "docProps/app.xml": (
            '<?xml version="1.0"?><Properties xmlns="http://schemas.openxmlformats.org/officeDocument/2006/extended-properties">'
            f"{app}</Properties>"
        ),
    }
    if custom_xml:
        parts["customXml/item1.xml"] = (
            '<?xml version="1.0"?><item xmlns="urn:custom">'
            '<data>AIGC:provenance</data></item>'
        )
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        for name, content in parts.items():
            zf.writestr(name, content)
    return buf.getvalue()


def build_odt(*, ai_generator: bool = False) -> bytes:
    generator = (
        '<meta:generator>Claude/2.0 LibreOffice</meta:generator>'
        if ai_generator
        else "<meta:generator>LibreOffice/7.4</meta:generator>"
    )
    parts = {
        "mimetype": "application/vnd.oasis.opendocument.text",
        "content.xml": (
            '<?xml version="1.0"?><office:document-content xmlns:office="urn:oasis:names:tc:opendocument:xmlns:office:1.0">'
            "<office:body><office:text><text:p>Hello</text:p></office:text></office:body>"
            "</office:document-content>"
        ),
        "meta.xml": (
            '<?xml version="1.0"?><office:document-meta xmlns:office="urn:oasis:names:tc:opendocument:xmlns:office:1.0" '
            'xmlns:meta="urn:oasis:names:tc:opendocument:xmlns:meta:1.0">'
            f"<office:meta>{generator}</office:meta></office:document-meta>"
        ),
        "styles.xml": (
            '<?xml version="1.0"?><office:document-styles xmlns:office="urn:oasis:names:tc:opendocument:xmlns:office:1.0"/>'
        ),
        "META-INF/manifest.xml": (
            '<?xml version="1.0"?><manifest:manifest xmlns:manifest="urn:oasis:names:tc:opendocument:xmlns:manifest:1.0"/>'
        ),
    }
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        for name, content in parts.items():
            zf.writestr(name, content)
    return buf.getvalue()


def build_pdf(*, with_xmp_ai: bool = False, with_ai_string: bool = False) -> bytes:
    """Minimal single-page PDF. XMP packet embedded raw (best-effort test)."""
    content = b"BT /F1 12 Tf 72 720 Td (Hello) Tj ET"
    objects = []
    objects.append(b"<< /Type /Catalog /Pages 2 0 R >>")
    objects.append(b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>")
    objects.append(
        b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] "
        b"/Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>"
    )
    objects.append(b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>")
    objects.append(
        b"<< /Length " + str(len(content)).encode() + b" >>\nstream\n" + content + b"\nendstream"
    )
    xmp = b""
    if with_xmp_ai:
        xmp = (
            b'<?xpacket begin="\xef\xbb\xbf" id="W5M0MpCehiHzreSzNTczkc9d"?>'
            b'<x:xmpmeta xmlns:x="adobe:ns:meta/"><rdf:RDF>'
            b"<rdf:Description>trainedAlgorithmicMedia</rdf:Description>"
            b"</rdf:RDF></x:xmpmeta>"
            b'<?xpacket end="w"?>'
        )
    ai_string = b"digitalSourceType=trainedAlgorithmicMedia" if with_ai_string else b""
    out = io.BytesIO()
    out.write(b"%PDF-1.4\n%\xe2\xe3\xcf\xd3\n")
    offsets = []
    for i, obj in enumerate(objects, start=1):
        offsets.append(out.tell())
        out.write(b"%d 0 obj\n" % i)
        out.write(obj)
        out.write(b"\nendobj\n")
    if xmp or ai_string:
        offsets.append(out.tell())
        out.write(b"%d 0 obj\n" % (len(objects) + 1))
        out.write(b"<< /Type /Metadata >>\nstream\n")
        out.write(xmp + ai_string)
        out.write(b"\nendstream\nendobj\n")
    xref_pos = out.tell()
    n = len(objects) + (1 if (xmp or ai_string) else 0)
    out.write(b"xref\n0 %d\n" % (n + 1))
    out.write(b"0000000000 65535 f \n")
    for off in offsets:
        out.write(("%010d 00000 n \n" % off).encode())
    out.write(b"trailer\n<< /Size %d /Root 1 0 R >>\n" % (n + 1))
    out.write(b"startxref\n%d\n%%%%EOF\n" % xref_pos)
    return out.getvalue()


TEXT_FIXTURES: dict[str, str] = {
    "zwsp": "Hello\u200bWorld\u00ad!",
    "bidi": "ab\u202eef\u202c end",
    "tag": "hi" + chr(0xE0041) + "there",
    "exotic_spaces": "a\u2003b\u3000c\u00a0d",
    "clean": "Normal ASCII and café — fine.",
    "emoji": "Balance \u2696\ufe0f Family \U0001F468\u200D\U0001F469\u200D\U0001F467",
}


def write_fixture(path: str, data: bytes) -> None:
    with open(path, "wb") as fh:
        fh.write(data)