"""Tests for container metadata clean: Markdown, HTML, SVG, DOCX, ODT, PDF."""

from __future__ import annotations

import sys
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from base import RemoveAiMarksBase
from container_meta import detect_container_format, inspect_container
from file_router import clean_file
from fixtures_builder import (
    build_docx,
    build_html,
    build_markdown,
    build_odt,
    build_pdf,
    build_svg,
)


class TestMarkdown(RemoveAiMarksBase):
    def test_inspect_ai_generator(self):
        src = self.write("ai.md", build_markdown(ai_generator=True))
        rep = inspect_container(src)
        self.assertTrue(rep.has_ai_metadata)
        self.assertTrue(any("frontmatter key: generator" in f for f in rep.findings))

    def test_inspect_ai_key(self):
        src = self.write("ai2.md", build_markdown(ai_key=True))
        rep = inspect_container(src)
        self.assertTrue(rep.has_ai_metadata)

    def test_inspect_clean(self):
        src = self.write("clean.md", build_markdown())
        rep = inspect_container(src)
        self.assertFalse(rep.has_ai_metadata)

    def test_clean_keeps_title(self):
        src = self.write("keep.md", build_markdown(ai_generator=True))
        out = self.tmp / "keep.cleaned.md"
        clean_file(src, output=out)
        text = out.read_text(encoding="utf-8")
        self.assertIn("title: Test", text)
        self.assertNotIn("generator: Claude", text)
        self.assertNotIn("ai_generated", text)

    def test_clean_verification_passed(self):
        src = self.write("v.md", build_markdown(ai_generator=True, ai_key=True))
        out = self.tmp / "v.cleaned.md"
        report = clean_file(src, output=out)
        self.assertEqual(report["verification"], "passed")
        self.verify_cleaned(report)


class TestHtml(RemoveAiMarksBase):
    def test_inspect_ai_meta(self):
        src = self.write("ai.html", build_html(ai_meta=True))
        rep = inspect_container(src)
        self.assertTrue(rep.has_ai_metadata)

    def test_inspect_jsonld(self):
        src = self.write("ld.html", build_html(jsonld=True))
        rep = inspect_container(src)
        self.assertTrue(rep.has_ai_metadata)

    def test_inspect_data_ai(self):
        src = self.write("da.html", build_html(data_ai=True))
        rep = inspect_container(src)
        self.assertTrue(rep.has_ai_metadata)

    def test_clean_removes_all_ai(self):
        src = self.write("all.html", build_html(ai_meta=True, jsonld=True, data_ai=True))
        out = self.tmp / "all.cleaned.html"
        report = clean_file(src, output=out)
        self.assertEqual(report["verification"], "passed")
        text = out.read_text(encoding="utf-8")
        self.assertNotIn("ChatGPT", text)
        self.assertNotIn("trainedAlgorithmicMedia", text)
        self.assertNotIn("data-ai", text)
        self.assertIn("<h1>Hi</h1>", text)

    def test_clean_clean_html_untouched(self):
        src = self.write("ok.html", build_html())
        out = self.tmp / "ok.cleaned.html"
        report = clean_file(src, output=out)
        self.assertEqual(report["verification"], "passed")
        self.assertIn("<h1>Hi</h1>", out.read_text(encoding="utf-8"))


class TestSvg(RemoveAiMarksBase):
    def test_inspect_metadata(self):
        src = self.write("ai.svg", build_svg(metadata=True))
        rep = inspect_container(src)
        self.assertTrue(rep.has_ai_metadata)

    def test_clean_removes_metadata(self):
        src = self.write("ai2.svg", build_svg(metadata=True, xmp=True, ai_comment=True))
        out = self.tmp / "ai2.cleaned.svg"
        report = clean_file(src, output=out)
        self.assertEqual(report["verification"], "passed")
        text = out.read_text(encoding="utf-8")
        self.assertNotIn("metadata", text)
        self.assertNotIn("xmpmeta", text)
        self.assertNotIn("generated by Claude", text)
        self.assertIn("<rect", text)

    def test_clean_clean_svg_untouched(self):
        src = self.write("ok.svg", build_svg())
        out = self.tmp / "ok.cleaned.svg"
        report = clean_file(src, output=out)
        self.assertEqual(report["verification"], "passed")
        self.assertIn("<rect", out.read_text(encoding="utf-8"))


class TestDocx(RemoveAiMarksBase):
    def test_inspect_ai_creator(self):
        src = self.write("ai.docx", build_docx(ai_creator=True))
        rep = inspect_container(src)
        self.assertTrue(rep.has_ai_metadata)

    def test_inspect_custom_xml(self):
        src = self.write("cx.docx", build_docx(custom_xml=True))
        rep = inspect_container(src)
        self.assertTrue(rep.has_ai_metadata)

    def test_clean_removes_ai(self):
        src = self.write("ai2.docx", build_docx(ai_creator=True, custom_xml=True))
        out = self.tmp / "ai2.cleaned.docx"
        report = clean_file(src, output=out)
        self.assertEqual(report["verification"], "passed")
        import zipfile

        with zipfile.ZipFile(out) as zf:
            names = zf.namelist()
            self.assertNotIn("customXml/item1.xml", names)
            core = zf.read("docProps/core.xml").decode("utf-8")
            self.assertNotIn("Claude", core)
            app = zf.read("docProps/app.xml").decode("utf-8")
            self.assertNotIn("Claude", app)

    def test_clean_keeps_body(self):
        src = self.write("body.docx", build_docx(ai_creator=True))
        out = self.tmp / "body.cleaned.docx"
        clean_file(src, output=out)
        import zipfile

        with zipfile.ZipFile(out) as zf:
            self.assertIn("<w:t>Hello</w:t>", zf.read("word/document.xml").decode("utf-8"))


class TestOdt(RemoveAiMarksBase):
    def test_inspect_ai_generator(self):
        src = self.write("ai.odt", build_odt(ai_generator=True))
        rep = inspect_container(src)
        self.assertTrue(rep.has_ai_metadata)

    def test_clean_removes_generator(self):
        src = self.write("ai2.odt", build_odt(ai_generator=True))
        out = self.tmp / "ai2.cleaned.odt"
        report = clean_file(src, output=out)
        self.assertEqual(report["verification"], "passed")
        import zipfile

        with zipfile.ZipFile(out) as zf:
            meta = zf.read("meta.xml").decode("utf-8")
            self.assertNotIn("Claude", meta)

    def test_clean_clean_odt_untouched(self):
        src = self.write("ok.odt", build_odt())
        out = self.tmp / "ok.cleaned.odt"
        report = clean_file(src, output=out)
        self.assertEqual(report["verification"], "passed")


class TestPdf(RemoveAiMarksBase):
    def test_inspect_xmp_ai(self):
        src = self.write("ai.pdf", build_pdf(with_xmp_ai=True))
        rep = inspect_container(src)
        self.assertTrue(rep.has_ai_metadata)

    def test_inspect_clean_pdf(self):
        src = self.write("ok.pdf", build_pdf())
        rep = inspect_container(src)
        self.assertFalse(rep.has_ai_metadata)

    def test_clean_best_effort(self):
        """PDF clean without exiftool is best-effort; report must be honest."""
        src = self.write("ai2.pdf", build_pdf(with_xmp_ai=True))
        out = self.tmp / "ai2.cleaned.pdf"
        report = clean_file(src, output=out)
        self.assertIn("verification", report)
        self.assertIn("note", report)
        self.assertTrue(out.exists())


class TestDetectFormat(unittest.TestCase):
    def test_detect_by_extension_and_magic(self):
        from pathlib import Path

        cases = [
            ("a.md", b"# hi", "markdown"),
            ("a.html", b"<html></html>", "html"),
            ("a.svg", b"<svg/>", "svg"),
            ("a.pdf", b"%PDF-1.4", "pdf"),
            ("a.docx", b"PK\x03\x04", "docx"),
            ("a.odt", b"PK\x03\x04", "odt"),
            ("a.txt", b"hello", "unknown"),
        ]
        for name, head, expected in cases:
            p = Path(name)
            self.assertEqual(detect_container_format(p, head), expected)


if __name__ == "__main__":
    unittest.main()