"""Unified inspect/clean for non-raster containers: SVG, PDF, DOCX, ODT, HTML, Markdown."""

from __future__ import annotations

import io
import re
import subprocess
import zipfile
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from common import classify_finding_confidence, safe_arg, safe_write_bytes, safe_write_text, subprocess_preexec_fn, which
from container_text import clean_html, clean_markdown, clean_svg, inspect_html, inspect_markdown, inspect_svg
from container_zip import clean_docx, clean_odt, inspect_docx, inspect_odt
from image_meta import C2PA_MARKERS, _contains_any, run_optional_tools

_XMP_PACKET_RE = re.compile(rb"<\?xpacket begin.*?<\?xpacket end[^?]*\?>", re.I | re.DOTALL)

AI_META_HINTS_AS_NEEDED = (
    b"c2pa",
    b"C2PA",
    b"digitalSourceType",
    b"trainedAlgorithmicMedia",
    b"compositeWithTrainedAlgorithmicMedia",
    b"algorithmicMedia",
    b"AIGC",
    b"aigc",
    b"AI generated",
    b"Generated by",
    b"Claude",
    b"Anthropic",
    b"OpenAI",
    b"SynthID",
    b"dcterms:provenance",
)


@dataclass
class ContainerInspectReport:
    path: str
    format: str
    has_c2pa: bool
    has_ai_metadata: bool
    findings: list[str] = field(default_factory=list)
    tools: dict[str, Any] = field(default_factory=dict)
    details: dict[str, Any] = field(default_factory=dict)
    notes: list[str] = field(default_factory=list)

    def to_dict(self) -> dict:
        return {
            "path": self.path,
            "format": self.format,
            "has_c2pa": self.has_c2pa,
            "has_ai_metadata": self.has_ai_metadata,
            "findings": self.findings,
            "findings_confidence": [classify_finding_confidence(f) for f in self.findings],
            "tools": self.tools,
            "details": self.details,
            "notes": self.notes,
        }


def detect_container_format(path: Path, data: bytes | None = None) -> str:
    ext = path.suffix.lower()
    if ext in (".svg",):
        return "svg"
    if ext in (".pdf",):
        return "pdf"
    if ext in (".docx",):
        return "docx"
    if ext in (".odt",):
        return "odt"
    if ext in (".html", ".htm"):
        return "html"
    if ext in (".md", ".markdown", ".mdx"):
        return "markdown"
    if data is not None:
        if data[:4] == b"%PDF":
            return "pdf"
        if data[:100].lstrip().startswith(b"<") and b"svg" in data[:500].lower():
            return "svg"
        if data[:2] == b"PK":
            try:
                with zipfile.ZipFile(io.BytesIO(data)) as zf:
                    names = set(zf.namelist())
                    if "word/document.xml" in names:
                        return "docx"
                    if "content.xml" in names and "meta.xml" in names:
                        return "odt"
            except zipfile.BadZipFile:
                pass
    return "unknown"


def _blob_hits(blob: bytes) -> tuple[bool, bool, list[str]]:
    lower = blob.lower()
    findings: list[str] = []
    has_c2pa = False
    has_ai = False
    for n in C2PA_MARKERS:
        if n.lower() in lower:
            has_c2pa = True
            findings.append(f"marker:{n.decode('ascii', errors='replace')}")
    for n in AI_META_HINTS_AS_NEEDED:
        if n.lower() in lower:
            has_ai = True
            label = n.decode("ascii", errors="replace")
            if label not in {f.split(":", 1)[-1] for f in findings}:
                findings.append(f"ai:{label}")
    return has_c2pa, has_ai or has_c2pa, findings[:30]


def _pdf_structured_blob(data: bytes) -> bytes:
    no_streams = re.sub(
        rb"stream\r?\n.*?endstream",
        b"stream endstream",
        data,
        flags=re.DOTALL,
    )
    xmp = b"\n".join(_XMP_PACKET_RE.findall(data))
    return no_streams + b"\n" + xmp


def inspect_pdf(path: Path, data: bytes) -> tuple[bool, bool, list[str], dict]:
    findings: list[str] = []
    has_c2pa, has_ai, hits = _blob_hits(_pdf_structured_blob(data))
    findings.extend(f"pdf-structured:{h}" for h in hits)
    xmp_blob = b"\n".join(_XMP_PACKET_RE.findall(data))
    if xmp_blob:
        findings.append("XMP packet present")
        has_ai = has_ai or bool(
            re.search(rb"digitalSourceType|trainedAlgorithmicMedia|SoftwareAgent|c2pa", xmp_blob, re.I)
        )
    tools = run_optional_tools(path)
    ct = tools.get("c2patool") or {}
    if ct.get("has_manifest"):
        has_c2pa = True
        findings.append("c2patool reports C2PA-related manifest")
    return has_c2pa, has_ai or has_c2pa, findings, {"tools": tools}


def clean_pdf(path: Path, dest: Path) -> tuple[list[str], dict]:
    actions: list[str] = []
    data = path.read_bytes()
    dest.parent.mkdir(parents=True, exist_ok=True)

    exiftool = which("exiftool")
    if exiftool:
        safe_write_bytes(dest, data)
        try:
            r = subprocess.run(
                [exiftool, "-all=", "-overwrite_original", safe_arg(str(dest))],
                capture_output=True,
                text=True,
                timeout=60,
                check=False,
                preexec_fn=subprocess_preexec_fn,
            )
            actions.append(f"exiftool -all= (rc={r.returncode})")
        except Exception as e:
            actions.append(f"exiftool failed: {e}")
        return actions, {"mode": "exiftool"}

    text = data
    new, n = re.subn(rb"<\?xpacket begin.*?<\?xpacket end[^?]*\?>", b"", text, flags=re.I | re.DOTALL)
    if n:
        actions.append(f"stripped XMP xpacket x{n} (degraded; may leave offsets broken)")
        safe_write_bytes(dest, new)
        actions.append("warning: pure-stdlib PDF strip is best-effort; prefer exiftool")
        return actions, {"mode": "stdlib-xmp", "degraded": True}

    safe_write_bytes(dest, data)
    actions.append(
        "no PDF cleaner available (install exiftool for reliable metadata strip); copied as-is"
    )
    return actions, {"mode": "copy", "degraded": True}


def inspect_container(path: Path) -> ContainerInspectReport:
    data = path.read_bytes()
    fmt = detect_container_format(path, data)
    tools: dict[str, Any] = {}
    details: dict[str, Any] = {}

    if fmt == "svg":
        has_c2pa, has_ai, findings, details = inspect_svg(data)
    elif fmt == "pdf":
        has_c2pa, has_ai, findings, details = inspect_pdf(path, data)
        tools = details.pop("tools", {})
    elif fmt == "docx":
        has_c2pa, has_ai, findings, details = inspect_docx(data)
    elif fmt == "odt":
        has_c2pa, has_ai, findings, details = inspect_odt(data)
    elif fmt == "html":
        text = data.decode("utf-8", errors="replace")
        has_c2pa, has_ai, findings, details = inspect_html(text)
    elif fmt == "markdown":
        text = data.decode("utf-8", errors="replace")
        has_c2pa, has_ai, findings, details = inspect_markdown(text)
    else:
        has_c2pa, has_ai, findings = False, False, [f"unsupported container: {fmt}"]
        details = {"unsupported": True}

    notes: list[str] = []
    if fmt == "pdf":
        notes.append("PDF inspection is best-effort; exiftool/c2patool give more reliable metadata detection")
    elif fmt == "docx":
        notes.append("DOCX: only metadata/provenance parts are scanned; visible body text is ignored")
    if "unsupported" in details:
        notes.append(f"format not fully inspected: {fmt}")

    if fmt in ("svg", "pdf", "docx") and not tools:
        tools = run_optional_tools(path)

    return ContainerInspectReport(
        path=str(path),
        format=fmt,
        has_c2pa=has_c2pa,
        has_ai_metadata=has_ai,
        findings=findings,
        tools=tools,
        details=details,
        notes=notes,
    )


def clean_container(path: Path, dest: Path, *, also_layer_a_text: bool = True) -> dict[str, Any]:
    from text_unicode import clean_text

    data = path.read_bytes()
    fmt = detect_container_format(path, data)
    actions: list[str] = []
    dest.parent.mkdir(parents=True, exist_ok=True)
    meta: dict[str, Any] = {"format": fmt}

    if fmt == "svg":
        cleaned, actions = clean_svg(data)
        safe_write_bytes(dest, cleaned)
    elif fmt == "pdf":
        actions, meta_extra = clean_pdf(path, dest)
        meta.update(meta_extra)
    elif fmt == "docx":
        cleaned, actions = clean_docx(data)
        safe_write_bytes(dest, cleaned)
    elif fmt == "odt":
        cleaned, actions = clean_odt(data)
        safe_write_bytes(dest, cleaned)
    elif fmt == "html":
        text = data.decode("utf-8", errors="surrogateescape")
        text, actions = clean_html(text)
        if also_layer_a_text:
            text2, stats = clean_text(text)
            if stats["removed_count"] or stats["replaced_count"]:
                actions.append(
                    f"layer A text: removed={stats['removed_count']} replaced={stats['replaced_count']}"
                )
                text = text2
        safe_write_text(dest, text)
    elif fmt == "markdown":
        text = data.decode("utf-8", errors="surrogateescape")
        text, actions = clean_markdown(text)
        if also_layer_a_text:
            text2, stats = clean_text(text)
            if stats["removed_count"] or stats["replaced_count"]:
                actions.append(
                    f"layer A text: removed={stats['removed_count']} replaced={stats['replaced_count']}"
                )
                text = text2
        safe_write_text(dest, text)
    else:
        raise ValueError(f"unsupported container format: {fmt}")

    after = inspect_container(dest)
    return {
        "input": str(path),
        "output": str(dest),
        "format": fmt,
        "actions": actions,
        "bytes_in": len(data),
        "bytes_out": dest.stat().st_size,
        "still_has_c2pa": after.has_c2pa,
        "still_has_ai_metadata": after.has_ai_metadata,
        "post_findings": after.findings,
        "meta": meta,
    }